In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------





In [0]:
from __future__ import print_function
import torch

## Tensors basic operations


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

Construct a 5x3 matrix, uninitialized tensor:

`` tensor.shape`` or ``tensor.size()`` returns the tensor´s dimensions --> [5,3]

``tensor.dtype`` returns tensor´s data type (int,float,....)



In [63]:
x = torch.empty(5, 3)
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

tensor([[3.8832e+29, 0.0000e+00, 1.4013e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [2.0000e+00, 3.0000e+00, 4.0000e+00],
        [5.0000e+00, 5.0664e+07, 3.9760e+12],
        [1.0333e+18, 1.9284e-33, 3.3243e-09]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Construct a randomly initialized matrix:



In [64]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4950, 0.2552, 0.2392],
        [0.8245, 0.0748, 0.6449],
        [0.3333, 0.2875, 0.0461],
        [0.7439, 0.2817, 0.2711],
        [0.6141, 0.1935, 0.5724]])


Construct a matrix filled zeros and of dtype long:



In [65]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [66]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [67]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)               # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2867, -1.7006,  1.7291],
        [-2.4640, -1.3613,  0.3905],
        [ 0.3458,  0.1265,  0.0784],
        [ 1.0384, -0.9545, -1.1614],
        [-0.4006,  0.6222, -1.8151]])


Get its size:



In [68]:
print(x.size())

torch.Size([5, 3])


``torch.Size`` is in fact a tuple, so it supports all tuple operations.

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

First syntax of addition



In [69]:
y = torch.rand(5, 3)
c = x + y
print("{}\n Tensor shape = {}\n Data type = {} ".format(c,c.shape,c.dtype))

tensor([[ 0.6039, -0.8927,  1.9363],
        [-2.2698, -0.5817,  1.3209],
        [ 0.9400,  0.9714,  0.1139],
        [ 1.3994, -0.0721, -0.7193],
        [-0.0519,  1.5408, -1.3401]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Second syntax of addition



In [70]:
c = torch.add(x, y)
print(x)

tensor([[ 0.2867, -1.7006,  1.7291],
        [-2.4640, -1.3613,  0.3905],
        [ 0.3458,  0.1265,  0.0784],
        [ 1.0384, -0.9545, -1.1614],
        [-0.4006,  0.6222, -1.8151]])


Addition: providing an output tensor as argument



In [71]:
c = torch.empty(5, 3)
torch.add(x, y, out=c)

print(x)

tensor([[ 0.2867, -1.7006,  1.7291],
        [-2.4640, -1.3613,  0.3905],
        [ 0.3458,  0.1265,  0.0784],
        [ 1.0384, -0.9545, -1.1614],
        [-0.4006,  0.6222, -1.8151]])


Addition: in-place



In [72]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.6039, -0.8927,  1.9363],
        [-2.2698, -0.5817,  1.3209],
        [ 0.9400,  0.9714,  0.1139],
        [ 1.3994, -0.0721, -0.7193],
        [-0.0519,  1.5408, -1.3401]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [73]:
print(x[:, 1])
print(x[0,0])
print(x[0:2,:-1])

tensor([-1.7006, -1.3613,  0.1265, -0.9545,  0.6222])
tensor(0.2867)
tensor([[ 0.2867, -1.7006],
        [-2.4640, -1.3613]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [74]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4888])
-0.48876604437828064


Create tensor within a range from 0 to 10.

In [75]:
x = torch.arange(10) 
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Create tensor as identity matrix  

In [76]:
x = torch.eye(3, 3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Conversion
------------

Converting a Torch Tensor to a NumPy array and vice versa is very easy.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array




In [77]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [78]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array b changed its values after a change in a



In [79]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [80]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [81]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], device='cuda:0')
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], dtype=torch.float64)


##Reshape a tensor
 If you want to resize/reshape tensor, you can use ``torch.view`` or ``torch.reshape``: 

We use the reshape function to change the shape of one (possibly multi-dimensional) array, to another that contains the same number of elements. For example, we can transform the shape of our line vector x to (3, 4), which contains the same values but interprets them as a matrix containing 3 rows and 4 columns. Note that although the shape has changed, the elements in x have not.

Fortunately, PyTorch can automatically work out one dimension given the other. We can invoke this capability by placing -1 for the dimension that we would like PyTorch to automatically infer. In our case, instead of ``x.reshape((2, 8))``, we could have equivalently used ``x.reshape((-1, 8))`` or ``x.reshape((2, -1))``


In [82]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [83]:
x = torch.randn(4, 4)
x = x.reshape((2, 8))
print(x)

tensor([[-2.1903,  0.1592, -0.8856, -0.3476, -1.6241, -0.6976,  0.0864, -0.3422],
        [ 0.9095,  0.5935, -0.9054,  2.0212, -1.5103, -0.4133, -0.2402,  0.0420]])


Change tensor axis

``view`` and ``permute`` are slighlty different operations. ``view`` changes the order of the tensors while ``permute`` only changes the axis.

In [84]:
x = torch.tensor([[1., 2., 3.],[4., 5., 6.]])

print(x.view(3, -1))

print(x.permute(1, 0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


Remove or add a fake dimension with ```squeeze() ``` and  ```unsqueeze() ``` operations, respectively.

```squeeze() ``` removes all 1-dimensional parts from a tensor and 
```squeeze(0) ``` removes the first dimension

In [85]:
x = torch.tensor([[1., 2., 3., 4., 5.]])
print(x.squeeze(0).shape)
print(x.unsqueeze(0).shape)

torch.Size([5])
torch.Size([1, 1, 5])


## Advanced operations


https://towardsdatascience.com/how-to-train-your-neural-net-tensors-and-autograd-941f2c4cc77c

https://www.codementor.io/@packt/how-to-perform-basic-operations-in-pytorch-code-10al39a4c4


https://towardsdatascience.com/how-to-train-your-neural-net-tensors-and-autograd-941f2c4cc77c



Get the sum of values in a tensor

In [86]:
torch.sum(x)

tensor(15.)

Get the mean value of a tensor

In [87]:
torch.mean(x)

tensor(3.)

Get the standard deviation value of a tensor

In [88]:
torch.std(x)

tensor(1.5811)

Get e^x values for a tensor

In [89]:
torch.exp(x)

tensor([[  2.7183,   7.3891,  20.0855,  54.5981, 148.4132]])

Find min/max value in a tensor

In [90]:
torch.max(x)

tensor(5.)

In [91]:
torch.min(x)

tensor(1.)

Indices of min and max values of a tensor

In [92]:
torch.argmin(x)

tensor(0)

In [93]:
torch.argmax(x)

tensor(4)

**Concatenation**

is another important operation that you need in your toolbox. Two tensors of the same size on all the dimensions except one, if required, can be concatenated using ```torch.cat```.

In [94]:
torch.cat((x,x))

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

Concatenate along second dimension ```dim=1 ```

In [95]:
torch.cat((x,x), dim=1)

tensor([[1., 2., 3., 4., 5., 1., 2., 3., 4., 5.]])

**Stack operation** 

looks very similar to concatenation but it is an entirely different operation. If you want to add a new dimension to your tensor, ```torch.stack()``` is the way to go. Similar to cat, you can pass the axis where you want to add the new dimension. However, make sure all the dimensions of the two tensors are the same other than the attaching dimension.

In [96]:
torch.stack((x,x), dim=0)

tensor([[[1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.]]])