# PyTorch Tensor operations
<a href="https://colab.research.google.com/github/iliasprc/pytorch-tutorials/blob/master/chapter1/2_autograd_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy that benefits from GPU's acceleration speed
-  A deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------





In [6]:
from __future__ import print_function
%matplotlib inline
import torch

## Tensors basic operations


Tensors are similar to NumPy’s ``ndarrays``, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

Construct a 5x3 matrix, uninitialized tensor with `` torch.empty(5,3)``:

In order to print the tensor's dimensions use

`` tensor.shape`` or ``tensor.size()`` --> `[5,3]`

``tensor.dtype`` returns tensor´s data type (int,float,....)



In [7]:
x = torch.empty(5, 3)
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.6299e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


To construct a randomly initialized matrix:
use ``torch.rand()



In [8]:
x = torch.rand(5, 3)

print(x)

tensor([[0.9866, 0.4132, 0.9046],
        [0.9079, 0.1236, 0.0385],
        [0.7843, 0.8959, 0.3232],
        [0.1255, 0.0187, 0.7412],
        [0.4056, 0.7794, 0.1496]])


Construct a matrix filled zeros:



In [9]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a tensor directly from an input list:



In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)               # result has the same size



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5169, -0.7904, -0.5119],
        [ 0.5389, -0.7781,  1.4935],
        [-0.1183, -0.6233,  0.3652],
        [ 1.6121, -0.4673, -1.7121],
        [ 0.9697, -1.2361,  0.7518]])


``torch.Size`` is in fact a tuple, so it supports all tuple operations.

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

First syntax of addition



In [12]:
y = torch.rand(5, 3)
c = x + y
print("{}\n Tensor shape = {}\n Data type = {} ".format(c,c.shape,c.dtype))

tensor([[ 1.0587, -0.5362,  0.1803],
        [ 0.7879,  0.0561,  1.5402],
        [ 0.6227, -0.2517,  0.5140],
        [ 1.7871, -0.4273, -1.6607],
        [ 1.6171, -1.1272,  1.6969]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Second syntax of addition



In [13]:
c = torch.add(x, y)
print(x)

tensor([[ 0.5169, -0.7904, -0.5119],
        [ 0.5389, -0.7781,  1.4935],
        [-0.1183, -0.6233,  0.3652],
        [ 1.6121, -0.4673, -1.7121],
        [ 0.9697, -1.2361,  0.7518]])


Addition: providing an output tensor as argument



In [14]:
c = torch.empty(5, 3)
torch.add(x, y, out=c)

print(x)

tensor([[ 0.5169, -0.7904, -0.5119],
        [ 0.5389, -0.7781,  1.4935],
        [-0.1183, -0.6233,  0.3652],
        [ 1.6121, -0.4673, -1.7121],
        [ 0.9697, -1.2361,  0.7518]])


Addition: in-place operations



In [15]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.0587, -0.5362,  0.1803],
        [ 0.7879,  0.0561,  1.5402],
        [ 0.6227, -0.2517,  0.5140],
        [ 1.7871, -0.4273, -1.6607],
        [ 1.6171, -1.1272,  1.6969]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [16]:
print(x[:, 1])
print(x[0,0])
print(x[0:2,:-1])

tensor([-0.7904, -0.7781, -0.6233, -0.4673, -1.2361])
tensor(0.5169)
tensor([[ 0.5169, -0.7904],
        [ 0.5389, -0.7781]])


If you have an one element tensor, you can use  ``.item()`` to get the value as a
Python number



In [17]:
x = torch.randn(1)
x
x.item()

1.015756607055664

Create tensor within a range from 0 to 10.

In [18]:
x = torch.arange(10) 
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create tensor as an identity matrix

In [19]:
x = torch.eye(3, 3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Conversion
------------

Converting a Torch Tensor to a NumPy array and vice versa is very easy.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array




In [20]:
a = torch.ones(5)
a
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

See how the numpy array b changed its values after a change in a



In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting numpy arrays to torch tensors

See how changing the np array changed the torch tensor automatically



In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the tensors on the CPU except a Chartensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [23]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], device='cuda:0')
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], dtype=torch.float64)


You can also use ``.cpu()`` and ``.cuda()`` to transfer tensors between cpu and gpu memory



torch.stack((x,x), dim=0)

In [28]:
torch.sum(x)

tensor(15.)

Get the mean value of a tensor

In [29]:
torch.mean(x)

tensor(3.)

Get the standard deviation value of a tensor

In [30]:
torch.std(x)

tensor(1.5811)

Get e^x values for a tensor

In [31]:
torch.exp(x)

tensor([[  2.7183,   7.3891,  20.0855,  54.5981, 148.4132]])

Find min/max value in a tensor

In [32]:
torch.max(x)

tensor(5.)

In [33]:
torch.min(x)

tensor(1.)

Indices of min and max values of a tensor

In [34]:
torch.argmin(x)

tensor(0)

In [35]:
torch.argmax(x)

tensor(4)

**Concatenation**

is another important operation that you need in your toolbox. Two tensors of the same size on all the dimensions except one, if required, can be concatenated using ```torch.cat```.

In [36]:
torch.cat((x,x))

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

Concatenate along second dimension ```dim=1 ```

In [37]:
torch.cat((x,x), dim=1)

tensor([[1., 2., 3., 4., 5., 1., 2., 3., 4., 5.]])

**Stack operation** 

looks very similar to concatenation but it is an entirely different operation. If you want to add a new dimension to your tensor, ```torch.stack()``` is the way to go. Similar to cat, you can pass the axis where you want to add the new dimension. However, make sure all the dimensions of the two tensors are the same other than the attaching dimension.

In [38]:
torch.stack((x,x), dim=0)

tensor([[[1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.]]])