In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------





In [0]:
from __future__ import print_function
import torch

## Tensors basic operations


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

Construct a 5x3 matrix, uninitialized tensor:

`` tensor.shape`` or ``tensor.size()`` returns the tensor´s dimensions --> [5,3]

``tensor.dtype`` returns tensor´s data type (int,float,....)



In [3]:
x = torch.empty(5, 3)
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

tensor([[2.9803e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

tensor([[0.6459, 0.8767, 0.6561],
        [0.2861, 0.6953, 0.5674],
        [0.7226, 0.3510, 0.2047],
        [0.0508, 0.8956, 0.3514],
        [0.4572, 0.1141, 0.6096]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.int64 


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

tensor([5.5000, 3.0000])
 Tensor shape = torch.Size([2])
 Data type = torch.float32 


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))               # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float64 
tensor([[ 1.9852,  0.4683,  1.8949],
        [ 0.6823, -0.9756,  1.4957],
        [-0.2229,  0.1676,  0.5474],
        [ 1.7583, -0.7898, -1.8078],
        [-0.7700, -0.1356, -0.7083]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


``torch.Size`` is in fact a tuple, so it supports all tuple operations.

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

First syntax of addition



In [9]:
y = torch.rand(5, 3)
c = x + y
print("{}\n Tensor shape = {}\n Data type = {} ".format(c,c.shape,c.dtype))

tensor([[ 2.5007,  1.0571,  2.5709],
        [ 0.8140, -0.2541,  1.6055],
        [-0.1389,  0.9288,  1.4285],
        [ 2.4776, -0.7703, -1.3917],
        [-0.5298, -0.0221, -0.2791]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Second syntax of addition



In [10]:
c = torch.add(x, y)
print("{}\n Tensor shape = {}\n Data type = {} ".format(c,c.shape,c.dtype))

tensor([[ 2.5007,  1.0571,  2.5709],
        [ 0.8140, -0.2541,  1.6055],
        [-0.1389,  0.9288,  1.4285],
        [ 2.4776, -0.7703, -1.3917],
        [-0.5298, -0.0221, -0.2791]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Addition: providing an output tensor as argument



In [11]:
c = torch.empty(5, 3)
torch.add(x, y, out=c)

print("{}\n Tensor shape = {}\n Data type = {} ".format(c,c.shape,c.dtype))

tensor([[ 2.5007,  1.0571,  2.5709],
        [ 0.8140, -0.2541,  1.6055],
        [-0.1389,  0.9288,  1.4285],
        [ 2.4776, -0.7703, -1.3917],
        [-0.5298, -0.0221, -0.2791]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.5007,  1.0571,  2.5709],
        [ 0.8140, -0.2541,  1.6055],
        [-0.1389,  0.9288,  1.4285],
        [ 2.4776, -0.7703, -1.3917],
        [-0.5298, -0.0221, -0.2791]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])
print(x[0,0])
print(x[0:2,:-1])

tensor([ 0.4683, -0.9756,  0.1676, -0.7898, -0.1356])
tensor(1.9852)
tensor([[ 1.9852,  0.4683],
        [ 0.6823, -0.9756]])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2521])
-1.2520800828933716


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array b changed its values after a change in a



In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.2521], device='cuda:0')
tensor([-0.2521], dtype=torch.float64)


## Advanced operations


https://towardsdatascience.com/how-to-train-your-neural-net-tensors-and-autograd-941f2c4cc77c

https://www.codementor.io/@packt/how-to-perform-basic-operations-in-pytorch-code-10al39a4c4


https://towardsdatascience.com/how-to-train-your-neural-net-tensors-and-autograd-941f2c4cc77c

unsqueeze

view 


permute