# PyTorch Tensor operations
<a href="https://colab.research.google.com/github/iliasprc/pytorch-tutorials/blob/master/chapter1/2_autograd_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy that benefits from GPU's acceleration speed
-  A deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------
In this chapter we will learn how to create Tensors as well as the main functions and operations.

In [1]:
from __future__ import print_function
%matplotlib inline
import torch

## Tensors basic operations
Tensors are very similar to NumPy’s ``ndarrays``, with the addition being that they can also be used on a GPU to accelerate computing.

In the following image you can see a visualization of Tensors with different dimensions

![tensor](./images/Pytorch_book_chapter1_tensor.jpg)


To construct a 5x3  uninitialized tensor you can use `` torch.empty(5,3)`` function:

In order to find the tensor's dimensions use

`` tensor.shape`` or ``tensor.size()`` --> `[5,3]`(``torch.Size`` is in fact a tuple, so it supports all tuple operations)
and  ``tensor.dtype`` to  tensor´s data type i.e. `int,float,....`



In [2]:
x = torch.empty(5, 3)
print("{}\n Tensor shape = {}\n Data type = {} ".format(x,x.shape,x.dtype))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


To initialize randomly a 2D matrix:
use ``torch.rand()``



In [3]:
x = torch.rand(5, 3)

print(x)

tensor([[0.1135, 0.0913, 0.2068],
        [0.2185, 0.0725, 0.6392],
        [0.1884, 0.5321, 0.2215],
        [0.5654, 0.3843, 0.5092],
        [0.1340, 0.7445, 0.9466]])


You can also construct a matrix filled with zeros:



In [4]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


If you have a list of numbers you can also convert it directly  to a tensor as follows:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Now we'll see how to create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. `dtype`, unless
new values are provided by user


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)               # result has the same size



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0783, -0.1138, -1.0502],
        [ 0.8579, -1.3289,  1.2822],
        [-1.0800,  1.0997, -1.1212],
        [-0.0168,  0.1981,  1.1926],
        [ 0.8912,  0.0356,  1.0509]])



## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

First syntax of matrix addition`(x+y)`



In [7]:
y = torch.rand(5, 3)
c = x + y
print("{}\n Tensor shape = {}\n Data type = {} ".format(c,c.shape,c.dtype))

tensor([[ 1.1996,  0.3733, -0.0518],
        [ 1.3634, -0.9041,  1.5322],
        [-0.9531,  2.0909, -1.0682],
        [ 0.5662,  0.9367,  1.3218],
        [ 1.1045,  0.6236,  1.0911]])
 Tensor shape = torch.Size([5, 3])
 Data type = torch.float32 


An alternative command is `torch.add(x,y)`:

In [8]:
c = torch.add(x, y)
print(x)

tensor([[ 1.0783, -0.1138, -1.0502],
        [ 0.8579, -1.3289,  1.2822],
        [-1.0800,  1.0997, -1.1212],
        [-0.0168,  0.1981,  1.1926],
        [ 0.8912,  0.0356,  1.0509]])


or provide an output tensor as argument:

In [9]:
c = torch.empty(5, 3)
torch.add(x, y, out=c)

print(x)

tensor([[ 1.0783, -0.1138, -1.0502],
        [ 0.8579, -1.3289,  1.2822],
        [-1.0800,  1.0997, -1.1212],
        [-0.0168,  0.1981,  1.1926],
        [ 0.8912,  0.0356,  1.0509]])


Addition: in-place operations



In [10]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1996,  0.3733, -0.0518],
        [ 1.3634, -0.9041,  1.5322],
        [-0.9531,  2.0909, -1.0682],
        [ 0.5662,  0.9367,  1.3218],
        [ 1.1045,  0.6236,  1.0911]])


Any operation that mutates a tensor in-place is post-fixed with an ``_``.
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.
You can use standard NumPy-like indexing in order to access any element of the tensor.



In [11]:
print(x[:, 1])
print(x[0,0])
print(x[0:2,:-1])

tensor([-0.1138, -1.3289,  1.0997,  0.1981,  0.0356])
tensor(1.0783)
tensor([[ 1.0783, -0.1138],
        [ 0.8579, -1.3289]])


If you have an one element tensor, you can use  ``.item()`` to get the value as a
Python number.



In [12]:
x = torch.randn(1)
x
x.item()

0.07749047875404358

Create tensor within a range from 0 to N using `torch.arange(N)`.

In [13]:
x = torch.arange(10) 
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an identity matrix

In [14]:
x = torch.eye(3, 3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])



NumPy Conversion
------------

Converting a Torch Tensor to a NumPy array and vice versa is very easy.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array




In [15]:
a = torch.ones(5)
a
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

See how the numpy array b changed its values after a change in a



In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting numpy arrays to torch tensors

See how changing the np array changed the torch tensor automatically



In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the tensors on the CPU except a Chartensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to()`` method.

Let's run the following  cell to check if any CUDA-capable device is available.
Then we  will use ``torch.device`` objects to move tensors in and out of the GPU.

In [18]:

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to()`` can also change dtype together!

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], device='cuda:0')
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]], dtype=torch.float64)


You can also use ``.cpu()`` and ``.cuda()`` to transfer tensors between cpu and gpu memory


**Read later:**

That was the first tutorial on Tensor's basic functions. In the next tutorial we will learn about
PyTorch's automatic differentiation `autograd`.
  For more  Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  check the following link  `https://pytorch.org/docs/torch`.