# PyTorch basics: tensor
In the first chapter, we have got a certain understanding of PyTorch through the official introductory tutorial.
This chapter will introduce the basic knowledge of PyTorch in detail.
After you have mastered all these basic knowledge, you can advance more quickly in the following applications.
If you already have a certain understanding of PyTorch, you can skip this chapter

In [40]:
# First introduce relevant packages
import torch
#Print the version
torch.__version__

'1.6.0'

## Tensor
As we describe in the previous chapter, Tensor is the basic operation unit in PyTorch.
It is the same as Numpy's ndarray and represents a multi-dimensional matrix.
The biggest difference with ndarray is that PyTorch's Tensor can run on the GPU, while numpy's ndarray can only
run on the CPU. Running on the GPU greatly speeds up the calculation.

Below we generate a simple tensor
Let's remind some of the basic operations we introduced earlier.

In [41]:
x = torch.rand(2, 3)
x

tensor([[0.9496, 0.0326, 0.3999],
        [0.0020, 0.4833, 0.2879]])

The above generated a matrix with 2 rows and 3 columns. Let's take a look at its size:

In [42]:
# You can use the same shape attribute as numpy to view
print(x.shape)
# You can also use the size() function, and the returned results are the same
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


Tensor is a multiple linear mapping defined on the Cartesian product of some vector spaces and some dual spaces.
Its coordinates are in |n|-dimensional space and a quantity with |n| components,
where each  component is a function of coordinates, and during coordinate transformation,
these components are also linearly transformed according to certain rules.
`r` is called the rank or order of the tensor (it has nothing to do with the rank and order of the matrix).


Let's generate some multi-dimensional tensors:

In [43]:
y=torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.1113, 0.4576, 0.3505, 0.2163, 0.5974],
          [0.4168, 0.4367, 0.5905, 0.1329, 0.8768],
          [0.5438, 0.3995, 0.8157, 0.2431, 0.1530],
          [0.0769, 0.3518, 0.3402, 0.1221, 0.3782]],

         [[0.1837, 0.3494, 0.1018, 0.9510, 0.6622],
          [0.0245, 0.0653, 0.6239, 0.4605, 0.2148],
          [0.0454, 0.3152, 0.9159, 0.3637, 0.8430],
          [0.6172, 0.4760, 0.4793, 0.5420, 0.1138]],

         [[0.9328, 0.3753, 0.2443, 0.6955, 0.8851],
          [0.5093, 0.1555, 0.6289, 0.6393, 0.8007],
          [0.5360, 0.7304, 0.5552, 0.3395, 0.1447],
          [0.4943, 0.2452, 0.3733, 0.5279, 0.5821]]],


        [[[0.7804, 0.5914, 0.0171, 0.2303, 0.1721],
          [0.9945, 0.4262, 0.7082, 0.3607, 0.8928],
          [0.0435, 0.2055, 0.8312, 0.3665, 0.9429],
          [0.8926, 0.9582, 0.3987, 0.0273, 0.4337]],

         [[0.6620, 0.1160, 0.8962, 0.2837, 0.0875],
          [0.6393, 0.3094, 0.0861, 0.7500, 0.5613],
          [0.2152, 0.2831, 0.5173, 0.9583, 0.1084],
  

The zeroth order tensor (r = 0) is a scalar ,
the first order tensor (r = 1) is a vector
and the second order tensor (r = 2) is a matrix while
the third order and above tensors (r >= 3) are  called a multi-dimensional tensors.

One thing to pay special attention to is the scalars:


In [44]:
#We directly use existing digital generation
scalar = torch.tensor(3.1433223)
print(scalar)
#Print scalar size
scalar.size()

tensor(3.1433)


torch.Size([])

For scalars, we can directly use `.item()` to retrieve the value of the corresponding

In [45]:
scalar.item()


3.143322229385376

Pay attention: If the tensor is initialised  with a list only one element in the tensor
we can also call the `tensor.item()` method. The only difference now is the size

In [46]:
tensor = torch.tensor([3.1433223])
tensor.item()
tensor.size()



torch.Size([1])

### Basic types
There are five basic data types of Tensor:
- 32-bit floating point type: `torch.FloatTensor`. (default)
- 64-bit integer: `torch.LongTensor`.
- 32-bit integer: `torch.IntTensor`.
- 16-bit integer: `torch.ShortTensor`.
- 64-bit floating point type: `torch.DoubleTensor`.

In addition to the above number types, there are
`torch.ByteTensor` (8-bit) and `torch.CharTensor`

In [47]:
long = tensor.long()
long

tensor([3])

In [48]:
half = tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [49]:
int_t=tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [50]:
flo = tensor.float()
flo

tensor([3.1433])

In [51]:
short = tensor.short()
short

tensor([3], dtype=torch.int16)

In [52]:
ch = tensor.char()
ch

tensor([3], dtype=torch.int8)

In [53]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

### Numpy conversion
Use numpy method to convert Tensor to ndarray

In [54]:
a = torch.randn((3, 2))
# tensor converted to numpy
numpy_a = a.numpy()
print(numpy_a)

[[ 2.0753376  -0.08061682]
 [ 1.1077912  -0.92455935]
 [-0.14099053  0.354406  ]]


Convert numpy to Tensor


In [55]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[ 2.0753, -0.0806],
        [ 1.1078, -0.9246],
        [-0.1410,  0.3544]])

Tensor and numpy objects share the same memory, so the conversion between them is fast and consumes almost no resources.
But this also means that if one of them changes, the other will also change.

### Switch between devices
Under normal circumstances, you can use the .cuda method to move tensor to gpu. This step requires cuda device support

In [56]:
cpu_a=torch.rand(4, 3)
cpu_a.type()

'torch.FloatTensor'

In [57]:
gpu_a=cpu_a.cuda()
gpu_a.type()

'torch.cuda.FloatTensor'

Use the `.cpu()` method to move tensor to cpu

In [58]:
cpu_b=gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'

If we have multiple GPUs, we can use the to method to determine which device to use with `torch.device(cuda:device_id)`
. Here is just a simple example:

In [59]:
#Use torch.cuda.is_available() to determine if there is a cuda device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
#Transfer tensor to device
gpu_b=cpu_b.to(device)
gpu_b.type()

cuda


'torch.cuda.FloatTensor'

### Initialization
There are many  initialization methods available in Pytorch.
Let's see the random initialization first.

In [60]:
# Use [0,1] to initialize a two-dimensional array randomly
rnd = torch.rand(5, 3)
rnd

tensor([[0.1370, 0.3020, 0.2490],
        [0.9052, 0.1449, 0.8814],
        [0.6225, 0.1218, 0.7992],
        [0.1710, 0.5384, 0.5160],
        [0.5533, 0.9356, 0.8533]])

To initialize a tensor with ones (1) use:

In [ ]:
##Initialize, use 1 to fill
one = torch.ones(2, 2)
one



and zeros as:

In [62]:


##Initialization, fill with 0
zero=torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

Now let's create an identity matrix where only the diagonal elements are equal to 1
and the rest equal to 0.

In [63]:
#Initialize an identity matrix, that is, the diagonal is 1 and the others are 0
eye=torch.eye(2,2)
eye

tensor([[1., 0.],
        [0., 1.]])

### Common methods
The operations API for tensors  is very similar to NumPy. If you are familiar with the operations in NumPy,
then they are basically the same:

In [64]:
x = torch.randn(3, 3)
x

tensor([[ 0.1391,  0.4317,  1.6309],
        [-1.2231, -1.0626,  0.6486],
        [ 0.3765, -1.5161,  0.6124]])

In [65]:
# Take the maximum value along the line
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

tensor([1.6309, 0.6486, 0.6124]) tensor([2, 2, 2])


In [66]:
# Each row x sum
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([ 2.2017, -1.6371, -0.5272])


In [67]:
y=torch.randn(3, 3)
z = x + y
print(z)




tensor([[ 0.3469,  3.2753,  0.1466],
        [-2.9494, -1.9053, -2.0406],
        [ 3.0602, -0.8539,  1.2648]])


## Reshape tensors
 If you want to resize/reshape tensor, you can use ``torch.view`` or ``torch.reshape``:

We use the reshape function to change the shape of one (possibly multi-dimensional) array,
to another that contains the
same number of elements. For example, we can transform the shape of our line vector x to (3, 4),
which contains the same values but interprets them as a matrix containing 3 rows and 4 columns.
Note that although the shape has changed, the elements in x have not.

Fortunately, PyTorch can automatically work out one dimension given the other.
We can invoke this capability by placing -1 for the dimension that we would like PyTorch to automatically infer.
In our case, instead of ``x.reshape((2, 8))``,
we could have equivalently used ``x.reshape((-1, 8))`` or ``x.reshape((2, -1))``


In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

In [ ]:
x = torch.randn(4, 4)
x = x.reshape((2, 8))
x

Change tensor axis
``view`` and ``permute`` are slightly different operations.
``view`` changes the order of the tensors whereas ``permute`` only changes the axis.

In [ ]:
x = torch.tensor([[1., 2., 3.],[4., 5., 6.]])

x.view(3, -1)

x.permute(1, 0)

Remove or add a fake dimension with ```squeeze() ``` and  ```unsqueeze() ``` operations, respectively.

```squeeze() ``` removes all 1-dimensional parts from a tensor and
```squeeze(0) ``` removes the first dimension

In [ ]:
x = torch.tensor([[1., 2., 3., 4., 5.]])
print(x.squeeze(0).shape)
print(x.unsqueeze(0).shape)




## Advanced operations on Tensors




Get the sum of values in a tensor

In [69]:
x = torch.randn(3, 3)
torch.sum(x)

tensor(0.1062)

Get the mean value of a tensor

In [70]:
torch.mean(x)

tensor(0.0118)

Get the standard deviation value of a tensor

In [71]:
torch.std(x)

tensor(1.2474)

Get e^x values for a tensor

In [72]:
torch.exp(x)

tensor([[0.4541, 0.1434, 1.7414],
        [5.8515, 4.4039, 0.2557],
        [0.6661, 1.8219, 1.2265]])

Find min/max value in a tensor

In [73]:
torch.max(x)

tensor(1.7667)

In [74]:
torch.min(x)

tensor(-1.9422)

Indices of min and max values of a tensor

In [75]:
torch.argmin(x)

tensor(1)

In [76]:
torch.argmax(x)

tensor(3)

**Concatenation**

is another important operation that you need in your toolbox.
Two tensors of the same size on all the dimensions except one, if required, can be concatenated using ```torch.cat```.

In [77]:
torch.cat((x,x))

tensor([[-0.7894, -1.9422,  0.5547],
        [ 1.7667,  1.4825, -1.3638],
        [-0.4064,  0.5999,  0.2042],
        [-0.7894, -1.9422,  0.5547],
        [ 1.7667,  1.4825, -1.3638],
        [-0.4064,  0.5999,  0.2042]])

Concatenate along second dimension ```dim=1 ```

In [78]:
torch.cat((x,x), dim=1)

tensor([[-0.7894, -1.9422,  0.5547, -0.7894, -1.9422,  0.5547],
        [ 1.7667,  1.4825, -1.3638,  1.7667,  1.4825, -1.3638],
        [-0.4064,  0.5999,  0.2042, -0.4064,  0.5999,  0.2042]])

 **Stack operation**:
looks very similar to concatenation but it is an entirely different operation.
If you want to add a new dimension to your tensor, ```torch.stack()``` is the way to go.
Similar to cat, you can pass the axis where you want to add the new dimension.
However, make sure all the dimensions of the two tensors are the same other than the attaching dimension.

In [79]:
torch.stack((x,x), dim=0)





tensor([[[-0.7894, -1.9422,  0.5547],
         [ 1.7667,  1.4825, -1.3638],
         [-0.4064,  0.5999,  0.2042]],

        [[-0.7894, -1.9422,  0.5547],
         [ 1.7667,  1.4825, -1.3638],
         [-0.4064,  0.5999,  0.2042]]])

The basic operations of tensors are almost introduced.
The next chapter introduces PyTorch's automatic derivative mechanism (autograd).

##### Useful links
https://towardsdatascience.com/how-to-train-your-neural-net-tensors-and-autograd-941f2c4cc77c

https://www.codementor.io/@packt/how-to-perform-basic-operations-in-pytorch-code-10al39a4c4


https://towardsdatascience.com/how-to-train-your-neural-net-tensors-and-autograd-941f2c4cc77c